composer:
	docker compose run --rm  php-cli composer

composer-install:
	docker compose run --rm  php-cli composer install

composer-dump:
	docker compose run --rm  php-cli composer dump-autoload

composer-require:
	docker compose run --rm  php-cli composer require