composer:
	docker compose run --rm  php-cli composer

composer-install:
	docker compose run --rm  php-cli composer install

composer-dump:
	docker compose run --rm  php-cli composer dump-autoload

composer-require:
	docker compose run --rm  php-cli composer require

cs-fixer:
	docker compose run --rm  php-cli ./vendor/bin/php-cs-fixer fix src