start:
	docker compose up -d --build

composer-install:
	docker compose run --rm  php-cli composer install

composer-dump:
	docker compose run --rm  php-cli composer dump-autoload

phpunit-tests:
	docker compose run --rm  php-cli ./vendor/bin/phpunit tests

cs-fixer:
	docker compose run --rm  php-cli ./vendor/bin/php-cs-fixer fix src

psalm:
	docker compose run --rm  php-cli ./vendor/bin/psalm